### ISSUE TITLE
Application not found

### ISSUE THREAD

**Issue by darkerheart** [EslaMx7/PasteIntoFiles#34]
When I try to right click > run PasteIntoFile it comes  up with "Application not found" by Explorer.EXE.

It was working fine before, and I've tried to reinstall it to fix the issue but I'm not sure what I'm doing wrong.

**Comment by JonasWinter** [comment]
Hey, basically the .exe creates some registry entries when it's run for the first time.
It could be possible that the location of your .exe has changed (changed drive letter or moved .exe or whatever).

However, you can fix it by adjusting the registry entries or simply deleting them and then re-running the .exe (as if you would run it for the first time).

The keys to delete / edit are:

- Computer\HKEY_CLASSES_ROOT\Directory\Background\shell\Paste Into File
- Computer\HKEY_CLASSES_ROOT\Directory\Background\shell\Paste Into File\command
- Computer\HKEY_CLASSES_ROOT\Directory\shell\Paste Into File
- Computer\HKEY_CLASSES_ROOT\Directory\shell\Paste Into File\command

I will have a look into the application and maybe add some kind of automation to fix this problem.

EDIT: As I saw in the readme.md, you can also run "PasteIntoFile /unreg" to  remove the registry entries and then re-run the .exe. It will then create new registry keys for the current location.


Kind regards,
Jonas

**Comment by darkerheart** [comment]
Thank you! Deleting the registry files and then reinstalling fixed it!
