### ISSUE TITLE
It'd be nice to Paste to Shortcut

### ISSUE THREAD

**Issue by FactEngineCommunity** [EslaMx7/PasteIntoFiles#38]
If I have a URL or a drive location in memory, it would be nice be able to paste to a shortcut.

**Comment by subz390** [comment]
In Windows 10 at least - once you have an image in the clipboard, context menu on a folder shortcut and the destination of the shortcut is inserted into the `Current location:` field of Paste Into File.

**Comment by FactEngineCommunity** [comment]
Hi, yeah I realised later that I could just right-click in a folder and add a shortcut quite easily. It might be overkill putting that functionality into Past to Shortcut. Let's close this one as not really necessary.
