### ISSUE TITLE
Feature Request: Use ctrl key to perform default action

### ISSUE THREAD

**Issue by David-Maisonave** [EslaMx7/PasteIntoFiles#44]
Use the **ctrl** key to perform the default action automatically without any further user input.

I recommend using ctrl key combination to have PasteIntoFile perform the default action automatically without having to prompt user with a dialog window.

Another option that would be good to have is an action for the **shift** key select, where when user holds the shift key while selecting "**Paste Into File**", a folder is appended to the Current Location field. The appended folder can be Text for text files and Image for image.
There can be and option to change the default appended folders via command line, like there is for /filename.

These two options could be made to work together so if user holds both **ctrl**-**shift** key while selecting "**Paste Into File**", it will create the file in the sub-folder automatically without prompting the user.

If needed, I could try to do the implementation myself.  I'm a C++ programmer and I've done modifications on a few C-sharp projects before.

**Comment by David-Maisonave** [comment]
I've created a new version of this program with the above changes:
See following fork:
https://github.com/David-Maisonave/PasteIntoFile

Please feel free to pull the changes into the main.

**Comment by EslaMx7** [comment]
@David-Maisonave Brilliant! what a great effort! Thank you very much, David, I will definitely pull it as soon as possible.

**Comment by David-Maisonave** [comment]
The version of PasteIntoFile in [eltos/PasteIntoFile](https://github.com/eltos/PasteIntoFile), uses the shift key for the no-popup option.
I rather that both versions have similar keyboard behavior, so I'm going to reverse the keys so that the shift key forces the no-popup and the ctrl key triggers creating the sub folder.

Also I'm going to add right mouse button logic to do the no-popup so that users can perform no-popup action without having to touch the keyboard.

**Comment by David-Maisonave** [comment]
I updated the code to switch ctrl and shift functionality, but I couldn't figure out how to get the right mouse button logic to work, so I'll have to leave that for another time.

I updated the README.md with info on the new logic.
